{
  inputs,
  ...
}:
{
  imports = [
    ./boot.nix
    ./flatpak.nix
    ./fonts.nix
    ./hardware.nix
    ./host-packages.nix
    ./network.nix
    ./nh.nix
    ./printing.nix
    ./greetd.nix
    ./security.nix
    ./services.nix
    ./stylix.nix
    ./system.nix
    ./thunar.nix
    ./user.nix
    ./virtualisation.nix
    ./xserver.nix
    inputs.stylix.nixosModules.stylix
  ];
}
